// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtXu_lKz0ZnOQfZJSA_anK7sd1UHn68G8',
    appId: '1:617135352154:web:750d8f169fbcbe178f6b63',
    messagingSenderId: '617135352154',
    projectId: 'tokoto-8943c',
    authDomain: 'tokoto-8943c.firebaseapp.com',
    storageBucket: 'tokoto-8943c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpfjf3AMo3hAvvBf10OR98g8v-pvbPHMs',
    appId: '1:617135352154:android:db1b8a120147479b8f6b63',
    messagingSenderId: '617135352154',
    projectId: 'tokoto-8943c',
    storageBucket: 'tokoto-8943c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTaiaJpwwetkm1GDxE9H353RAizgin7jE',
    appId: '1:617135352154:ios:8b4f5d8702509d378f6b63',
    messagingSenderId: '617135352154',
    projectId: 'tokoto-8943c',
    storageBucket: 'tokoto-8943c.appspot.com',
    iosBundleId: 'com.example.tokoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTaiaJpwwetkm1GDxE9H353RAizgin7jE',
    appId: '1:617135352154:ios:0d57a77f0f743e7f8f6b63',
    messagingSenderId: '617135352154',
    projectId: 'tokoto-8943c',
    storageBucket: 'tokoto-8943c.appspot.com',
    iosBundleId: 'com.example.tokoto.RunnerTests',
  );
}
