import 'package:get/get.dart';
class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "Flash Deal": "Flash Deal",
    "Bill": "Bill",
    "Game": "Game",
    "Daily Gifting": "Daily Gift",
    "More": "More",
    "Special for you": "Special for you",
    "See More": "See More",
    "Popular Products": "Popular Products",
    "Categories": "Categories",
    "Search Product": "Search Product",
    "A Summer Surprise": "A Summer Surprise",
    "Your Cart": "Your Cart",
    "items": "items",
    "Total": "Total",
    "Add voucher code": "Add voucher code",
    "Check Out": "Check Out",
    "Your cart is empty": "Your cart is empty",
    "Favorites": "Favorites",
    "Products": "Products",
    "Product Details": "Product Details",
    "Profile": "Profile",
    "My Account": "My Account",
    "Notifications": "Notifications",
    "Settings": "Settings",
    "Help Center": "Help Center",
    "Log Out": "Log Out",
    "Cashback 20%": "Cashback 20%",
    "Grab The Deals": "Grab The Deals",
    "Grab Crazy Deals!!": "Grab Crazy Deals!!",
    "Heavy Discounts!!": "Heavy Discounts!!",
    "Tap the Target!": "Tap the Target!",
    "Tap!!": "Tap!!",
    "Score": "Score",
    "Time Left": "Time Left",
    "Start Game": "Start Game",
    "Spin the Wheel": "Spin the Wheel",
    "Spin": "Spin",
    "Chat": "Chat",
    "Chat Page": "Chat Page",
    "Account Details": "Account Details",
    "Profile Picture": "Profile Picture",
    "Email": "Email",
    "username": "username",
    "Full-Name": "Full-Name",
    "Phone-Number": "Phone-Number",
    "Primary-Address": "Primary-Address",
    "Points": "Points",
    "FAQ": "FAQ",
    "How can I provide feedback or suggest...": "How can I provide feedback or suggest...",
    "You can provide feedback or suggestions by contacting our support team through the contact form on our website.": "You can provide feedback or suggestions by contacting our support team through the contact form on our website.",
    "Is there a free trial available?": "Is there a free trial available?",
    "Yes, we offer a 7-day free trial for all new users. You can sign up on our website to start your free trial.": "Yes, we offer a 7-day free trial for all new users. You can sign up on our website to start your free trial.",
    "How can I contact customer support?": "How can I contact customer support?",
    "You can contact customer support through our support email at support@example.com or call us at 1-800-123-4567.": "You can contact customer support through our support email at support@example.com or call us at 1-800-123-4567.",
    "What payment methods do you accept?": "What payment methods do you accept?",
    "We accept various payment methods including credit cards, PayPal, and bank transfers.": "We accept various payment methods including credit cards, PayPal, and bank transfers.",
    "Can I upgrade or downgrade my plan?": "Can I upgrade or downgrade my plan?",
    "Yes, you can upgrade or downgrade your plan at any time through your account settings.": "Yes, you can upgrade or downgrade your plan at any time through your account settings.",
    "Is my personal information secure?": "Is my personal information secure?",
    "Yes, we take your privacy and security very seriously. All personal information is encrypted and securely stored.": "Yes, we take your privacy and security very seriously. All personal information is encrypted and securely stored.",
    "Welcome Back": "Welcome Back",
    "Sign in with your email and password\n      or continue with social media":"Sign in with your email and password\n      or continue with social media",
    "Enter your email": "Enter your email",
    "Enter your password": "Enter your password",
    "Password": "Password",
    "Remember me": "Remember me",
    "Forgot Password": "Forgot Password",
    "Sign In": "Sign In",
    "I do not have an account":"Don't have an account?",
    "Continue":"Continue",
    "Register Account": "Register Account",
    "Complete your details or continue\n              with social media": "Complete your details or continue\n              with social media",
    "Re-enter your password": "Re-enter your password",
    "Confirm Password":  "Confirm Password",
    "By continuing your confirm that you agree\n            with our Term and condition": "By continuing your confirm that you agree\n            with our Term and condition",
    "Please enter your email and we will send\n      you a link to return to your account": "Please enter your email and we will send\n      you a link to return to your account",
    "Login Success": "Login Success",
    "Back to home": "Back to home",
    "Edit": "Edit",
    "Cancel": "Cancel",
    "Save": "Save",
    "Language Changed successfully": "Language Changed successfully",
    "Choose a Language": "Choose a Language",
    "Change Language": "Change Language"
    },
    'hi': {
       "Flash Deal": "फ्लैश डील",
    "Bill": "बिल",
    "Game": "खेल",
    "Daily Gift": "दैनिक उपहार",
    "More": "अधिक",
    "Special for you": "आपके लिए विशेष",
    "See More": "और देखें",
    "Popular Products": "लोकप्रिय उत्पाद",
    "Categories": "श्रेणियाँ",
    "Search Product": "उत्पाद खोजें",
    "A Summer Surprise": "एक ग्रीष्मकालीन आश्चर्य",
    "Your Cart": "आपकी गाड़ी",
    "items": "आइटम",
    "Total": "कुल",
    "Add voucher code": "वाउचर कोड जोड़ें",
    "Check Out": "चेक आउट",
    "Your cart is empty": "आपकी गाड़ी खाली है",
    "Favorites": "पसंदीदा",
    "Products": "उत्पाद",
    "Product Details": "उत्पाद विवरण",
    "Profile": "प्रोफ़ाइल",
    "My Account": "मेरा खाता",
    "Notifications": "सूचनाएं",
    "Settings": "सेटिंग्स",
    "Help Center": "सहायता केंद्र",
    "Log Out": "लॉग आउट",
    "Cashback 20%": "कैशबैक 20%",
    "Grab The Deals": "सौदों को पकड़ें",
    "Grab Crazy Deals!!": "पागल सौदों को पकड़ें!!",
    "Heavy Discounts!!": "भारी छूट!!",
    "Tap the Target!": "लक्ष्य पर टैप करें!",
    "Tap!!": "टैप!!",
    "Score": "स्कोर",
    "Time Left": "समय बचा है",
    "Start Game": "खेल शुरू करें",
    "Spin the Wheel": "पहिया घुमाएं",
    "Spin": "घुमाएँ",
    "Chat": "चैट",
    "Chat Page": "चैट पेज",
    "Account Details": "खाता विवरण",
    "Profile Picture": "प्रोफ़ाइल चित्र",
    "Email": "ईमेल",
    "username": "उपयोगकर्ता नाम",
    "Full-Name": "पूरा नाम",
    "Phone-Number": "फ़ोन नंबर",
    "Primary-Address": "प्राथमिक पता",
    "Points": "अंक",
    "FAQ": "सामान्य प्रश्न",
    "How can I provide feedback or suggest...": "मैं प्रतिक्रिया या सुझाव कैसे प्रदान कर सकता हूँ...",
    "You can provide feedback or suggestions by contacting our support team through the contact form on our website.": "आप हमारी वेबसाइट पर संपर्क फॉर्म के माध्यम से हमारी सहायता टीम से संपर्क करके प्रतिक्रिया या सुझाव प्रदान कर सकते हैं।",
    "Is there a free trial available?": "क्या एक निःशुल्क परीक्षण उपलब्ध है?",
    "Yes, we offer a 7-day free trial for all new users. You can sign up on our website to start your free trial.": "हां, हम सभी नए उपयोगकर्ताओं के लिए 7-दिन का निःशुल्क परीक्षण प्रदान करते हैं। आप हमारी वेबसाइट पर साइन अप करके अपना निःशुल्क परीक्षण शुरू कर सकते हैं।",
    "How can I contact customer support?": "मैं ग्राहक सहायता से कैसे संपर्क कर सकता हूँ?",
    "You can contact customer support through our support email at support@example.com or call us at 1-800-123-4567.": "आप हमारी सहायता ईमेल support@example.com पर या हमें 1-800-123-4567 पर कॉल करके ग्राहक सहायता से संपर्क कर सकते हैं।",
    "What payment methods do you accept?": "आप कौनसे भुगतान तरीके स्वीकार करते हैं?",
    "We accept various payment methods including credit cards, PayPal, and bank transfers.": "हम विभिन्न भुगतान तरीकों को स्वीकार करते हैं जिनमें क्रेडिट कार्ड, PayPal और बैंक स्थानांतरण शामिल हैं।",
    "Can I upgrade or downgrade my plan?": "क्या मैं अपनी योजना को उन्नत या निम्नतर कर सकता हूँ?",
    "Yes, you can upgrade or downgrade your plan at any time through your account settings.": "हां, आप किसी भी समय अपने खाता सेटिंग्स के माध्यम से अपनी योजना को उन्नत या निम्नतर कर सकते हैं।",
    "Is my personal information secure?": "क्या मेरी व्यक्तिगत जानकारी सुरक्षित है?",
    "Yes, we take your privacy and security very seriously. All personal information is encrypted and securely stored.": "हां, हम आपकी गोपनीयता और सुरक्षा को बहुत गंभीरता से लेते हैं। सभी व्यक्तिगत जानकारी एन्क्रिप्ट की गई है और सुरक्षित रूप से संग्रहीत की गई है।",
    "Welcome Back": "वापसी पर स्वागत है",
    "Sign in with your email and password\n      or continue with social media":"अपने ईमेल और पासवर्ड के साथ साइन इन करें\n      या सोशल मीडिया के साथ जारी रखें",
    "Enter your email": "अपना ईमेल दर्ज करें",
    "Enter your password": "अपना पासवर्ड दर्ज करें",
    "Password": "पासवर्ड",
    "Remember me": "मुझे याद रखें",
    "Forgot Password": "पासवर्ड भूल गए",
    "Sign In": "साइन इन करें",
    "Sign Up":"સાઇન અપ",
    "I do not have an account": "खाता नहीं है?",
    "Continue":"जारी रखें",
    "Register Account": "खाता पंजीकृत करें",
    "Complete your details or continue\n              with social media": "अपना विवरण पूरा करें या सोशल मीडिया के साथ\n              जारी रखें",
    "Re-enter your password": "अपना पासवर्ड पुनः दर्ज करें",
    "Confirm Password":  "पासवर्ड की पुष्टि करें",
    "By continuing your confirm that you agree\n            with our Term and condition": "जारी रखने से आप हमारे नियम और शर्तों के साथ\n            सहमत होने की पुष्टि करते हैं",
    "Please enter your email and we will send\n      you a link to return to your account": "कृपया अपना ईमेल दर्ज करें और हम आपको अपने खाते में वापस लौटने के लिए एक लिंक भेजेंगे",
    "Login Success": "लॉगिन सफल",
    "Back to home": "वापस घर",
    "Edit": "संपादित करें",
    "Cancel": "रद्द करें",
    "Save": "सहेजें",
    "Language Changed successfully": "भाषा सफलतापूर्वक बदली गई",
    "Choose a Language":"एक भाषा चुनें",
    "Change Language":"भाषा बदलें"
    },
    'gu': {
      "Flash Deal": "ફ્લેશ ડીલ",
    "Bill": "બિલ",
    "Game": "ગેમ",
    "Daily Gift": "દૈનિક ભેટ",
    "More": "વધુ",
    "Special for you": "તમારા માટે ખાસ",
    "See More": "વધુ જુઓ",
    "Popular Products": "લોકપ્રિય ઉત્પાદનો",
    "Categories": "શ્રેણીઓ",
    "Search Product": "ઉત્પાદન શોધો",
    "A Summer Surprise": "એક ઉનાળાની આશ્ચર્ય",
    "Your Cart": "તમારી કાર્ટ",
    "items": "વસ્તુઓ",
    "Total": "કુલ",
    "Add voucher code": "વાઉચર કોડ ઉમેરો",
    "Check Out": "ચેક આઉટ",
    "Your cart is empty":"તમારું ટોપલું ખાલી છે",
    "Favorites": "મનપસંદ",
    "Products": "ઉત્પાદનો",
    "Product Details": "ઉત્પાદન વિગતો",
    "Profile": "પ્રોફાઇલ",
    "My Account": "મારું એકાઉન્ટ",
    "I do not have an account": "કોઈ ખાતું નથી?",
    "Notifications": "સૂચનાઓ",
    "Settings": "સેટિંગ્સ",
    "Help Center": "મદદ કેન્દ્ર",
    "Log Out": "લોગ આઉટ",
    "Cashback 20%": "કેશબેક 20%",
    "Grab The Deals": "સોદા પકડો",
    "Grab Crazy Deals!!": "ક્રેઝી ડીલ્સ પકડો!!",
    "Heavy Discounts!!": "ભારે છૂટ!!",
    "Tap the Target!": "ટાર્ગેટ પર ટેપ કરો!",
    "Tap!!": "ટેપ!!",
    "Score": "સ્કોર",
    "Time Left": "સમય બાકી છે",
    "Start Game": "ગેમ શરૂ કરો",
    "Spin the Wheel": "વ્હીલ ફેરવો",
    "Spin": "ફેરવો",
    "Chat": "ચેટ",
    "Chat Page": "ચેટ પેજ",
    "Account Details": "ખાતું વિગતો",
    "Profile Picture": "પ્રોફાઇલ ચિત્ર",
    "Email": "ઇમેઇલ",
    "username": "વપરાશકર્તા નામ",
    "Full-Name": "પૂર્ણ નામ",
    "Phone-Number": "ફોન નંબર",
    "Primary-Address": "પ્રાથમિક સરનામું",
    "Points": "પોઈન્ટ્સ",
    "FAQ": "એફએક્યુ",
    "How can I provide feedback or suggest...": "હું પ્રતિસાદ કે સૂચનો કેવી રીતે આપી શકું...",
    "You can provide feedback or suggestions by contacting our support team through the contact form on our website.": "વેબસાઇટ પરના સંપર્ક ફોર્મ દ્વારા અમારી સપોર્ટ ટીમનો સંપર્ક કરીને તમે પ્રતિસાદ અથવા સૂચનો આપી શકો છો.",
    "Is there a free trial available?": "શું કોઈ નિ:शुલ્ક અજમાયશ ઉપલબ્ધ છે?",
    "Yes, we offer a 7-day free trial for all new users. You can sign up on our website to start your free trial.":"હા, અમે બધા નવા વપરાશકર્તાઓ માટે 7-દિવસની મફત અજમાયશ ઓફર કરીએ છીએ. તમે તમારી મફત અજમાયશ શરૂ કરવા માટે અમારી વેબસાઇટ પર સાઇન અપ કરી શકો છો.",
    "How can I contact customer support?": "હું ગ્રાહક સપોર્ટનો સંપર્ક કેવી રીતે કરી શકું?",
    "You can contact customer support through our support email at support@example.com or call us at 1-800-123-4567.": "તમે અમારા સપોર્ટ ઇમેલ support@example.com પર અથવા 1-800-123-4567 પર કૉલ કરીને ગ્રાહક સપોર્ટનો સંપર્ક કરી શકો છો.",
    "What payment methods do you accept?": "તમે કઈ ચુકવણી પદ્ધતિઓ સ્વીકારો છો?",
    "We accept various payment methods including credit cards, PayPal, and bank transfers.": "અમે ક્રેડિટ કાર્ડ્‌સ, પેપાલ અને બેંક ટ્રાન્સફર સહિત વિવિધ ચુકવણી પદ્ધતિઓ સ્વીકારીએ છીએ.",
    "Can I upgrade or downgrade my plan?": "શું હું મારી યોજનાનું નवीનીકરણ અથવા ઘટાડો કરી શકું છું?",
    "Yes, you can upgrade or downgrade your plan at any time through your account settings.": "હા, તમે તમારી એકાઉન્ટ સેટિંગ્‌ઝ દ્વારા કોઈપણ સમયે તમારી યોજનાનું નવીનીકરણ અથવા ઘટાડો કરી શકો છો.",
    "Is my personal information secure?": "શું મારી વ્યક્તિગત માહિતી સુરક્ષિત છે?",
    "Yes, we take your privacy and security very seriously. All personal information is encrypted and securely stored.": "હા, અમે તમારી ગોપનીયતા અને સુરક્ષાને ખૂબ જ ગંભીરતાથી લઈએ છીએ. તમામ વ્યક્તિગત માહિતી એન્ક્રિપ્ટेड અને સુરક્ષિત રીતે સંગ્રહિત કરવામાં આવે છે.",
    "Welcome Back":"ફરી સ્વાગત છે",

    "Register Account":"રજીસ્ટર એકાઉન્ટ",
    "Continue":"ચાલુ રાખો",
    "Complete your details or continue\n              with social media":"તમારી વિગતો પૂર્ણ કરો અથવા\n              સોશિયલ મીડિયા સાથે ચાલુ રાખો",
    "Re-enter your password":"તમારો પાસવર્ડ ફરીથી દાખલ કરો",
    "Confirm Password":"પાસવર્ડની પુષ્ટિ કરો",
    "By continuing your confirm that you agree\n            with our Term and condition": "તમારી પુષ્ટિ ચાલુ રાખીને કે તમે\n            અમારી શરતો અને શરતો સાથે સંમત છો",

    "Sign in with your email and password\n      or continue with social media":  "તમારા ઇમેલ અને પાસવર્ડ સાથે સાઇન ઇન કરો\n      અથવા તમે સોશિયલ મીડિયા સાથે આગળ વધો",
    "Enter your email": "તમારું ઇમેલ દાખલ કરો",
    "Enter your password": "તમારું પાસવર્ડ દાખલ કરો",
    "Please enter your email and we will send\n      you a link to return to your account":"કૃપા કરીને તમારો ઇમેઇલ દાખલ કરો અને અમે\n       તમને તમારા એકાઉન્ટ પર પાછા જવા માટે એક લિંક મોકલીશું",
    "Password": "પાસવર્ડ",
    "Remember me": "મને યાદ રાખો",
    "Forgot Password": "પાસવર્ડ વિસરાઈ ગયું",
    "Sign In": "સાઇન ઇન કરો",
    "Sign Up": "સાઇન અપ કરો",
    "Language Changed successfully": "ભાષા સફળતાપૂર્વક બદલાઈ",
    "Choose a Language":"એક ભાષા પસંદ કરો",
    "Change Language": "ભાષા બદલો"
    }
  };
}